# Generated by Django 5.0.6 on 2024-07-11 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_player_email_alter_player_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
